### ISSUE TITLE
 error during sbt launcher: `java.lang.UnsupportedOperationException`: The Security Manager is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by wucke13** [zaninime/sbt-derivation#17]
Trying to build https://github.com/Systems-Modeling/SysML-v2-API-Services, I get an error about the deprecation of the Security Manager. This sounds like a too new java version is used. Therefore I tried overriding the java version, by putting the following into the argumen attributest of `mkSbtDerivation`: 

```nix
{
  # ...
  sbt = pkgs.sbt.override { jre = pkgs.jdk17_headless; };
  #...
}
```
However, that does not seem to affect the result. Here are my flake inputs, if anyone is wondering:
````
Inputs:
├───flake-utils: github:numtide/flake-utils/ff7b65b44d01cf9ba6a71320833626af21126384
│   └───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e
├───nixpkgs: github:NixOS/nixpkgs/34bdaaf1f0b7fb6d9091472edc968ff10a8c2857
└───sbt: github:zaninime/sbt-derivation/6762cf2c31de50efd9ff905cbcc87239995a4ef9
    ├───flake-utils: github:numtide/flake-utils/5aed5285a952e0b949eb3ba02c12fa4fcfef535f
    └───nixpkgs follows input 'nixpkgs'
````

The actual error log:

```console
SysML-v2-API-Services-sbt-dependencies.tar.zst> unpacking sources
SysML-v2-API-Services-sbt-dependencies.tar.zst> unpacking source archive /nix/store/w778dcqc88ngkv4ng271yyks4rqh0fyd-source
SysML-v2-API-Services-sbt-dependencies.tar.zst> source root is source
SysML-v2-API-Services-sbt-dependencies.tar.zst> patching sources
SysML-v2-API-Services-sbt-dependencies.tar.zst> building
SysML-v2-API-Services-sbt-dependencies.tar.zst> running:
SysML-v2-API-Services-sbt-dependencies.tar.zst> > sbt compile
SysML-v2-API-Services-sbt-dependencies.tar.zst> ...to warm up the dependencies' caches
SysML-v2-API-Services-sbt-dependencies.tar.zst> copying runtime jar...
SysML-v2-API-Services-sbt-dependencies.tar.zst> [info] [launcher] getting org.scala-sbt sbt 1.2.8  (this may take some time)...
SysML-v2-API-Services-sbt-dependencies.tar.zst> [info] [launcher] getting Scala 2.12.7 (for sbt)...
SysML-v2-API-Services-sbt-dependencies.tar.zst> java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at java.base/java.lang.System.setSecurityManager(System.java:425)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at sbt.TrapExit$.installManager(TrapExit.scala:53)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at sbt.StandardMain$.runManaged(Main.scala:128)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at sbt.xMain.run(Main.scala:89)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Launch$.run(Launch.scala:149)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Launch$.launch(Launch.scala:159)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Launch$.apply(Launch.scala:44)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Launch$.apply(Launch.scala:21)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Boot$.runImpl(Boot.scala:78)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Boot$.run(Boot.scala:73)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Boot$.main(Boot.scala:21)
SysML-v2-API-Services-sbt-dependencies.tar.zst>         at xsbt.boot.Boot.main(Boot.scala)
SysML-v2-API-Services-sbt-dependencies.tar.zst> [error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
```

**Comment by zaninime** [comment]
Can you please provide an example project? I'm not sure how you overwrote the `sbt` version. Also please note that 17 might be too recent, too: https://github.com/sbt/sbt/issues/6558

**Comment by wucke13** [comment]
@zaninime Sure! What a pleasently quick response :heart: https://github.com/DLR-FT/sysml-v2-nix

**Comment by zaninime** [comment]
This has no effect: https://github.com/DLR-FT/sysml-v2-nix/blob/main/flake.nix#L21. It might seem confusing at first, however this is the function you're calling and if you pass anything to it, it will end up in the build environment, but not on the path, which is what you want in this case.

To override the args in the first parameter of the function in [this file](https://github.com/zaninime/sbt-derivation/blob/master/lib/sbt-derivation.nix) (lines 1-6 basically), there's a trick via https://github.com/zaninime/sbt-derivation/blob/master/lib/bootstrap.nix which is similar to how python or other ecosystem are coded in nixpkgs. You can try to do `(sbt.mkSbtDerivation.${system}.withOverrides { sbt = <your sbt goes here>; }) { pname = "..."; // etc }`

**Comment by wucke13** [comment]
That did definitely work, and brought me to the next problem: ` java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI`

**Comment by wucke13** [comment]
@zaninime  As you hinted, OpenJDK 11 fixes the issue. Thank you for the quick help! Long live the legacy... :smiling_face_with_tear:

**Comment by zaninime** [comment]
I'm happy you managed :) legacy ftw 😉
